version: 2.1
jobs:
  build:
    working_directory: ~/circleci/device-management-app
    docker:
      - image: circleci/openjdk:11-stretch
    steps:
      - checkout
      - restore_cache:
          key: circleci-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/device-management-app-0.0.1-SNAPSHOT.jar